### ISSUE TITLE
Recomendacion

### ISSUE THREAD

**Issue by SimonMirleni** [pdepviernestm/presentacion-2022-BrunoRizzo765#1]
Hola Bruno, ¿cómo andas? Muy buena presentación. Lo único que sumaría es hacer un punteo de tus datos personales (como hiciste en la sección de hobbies).
![](https://media1.giphy.com/media/H7TsKHN6xAoAy96fJr/giphy.gif?cid=ecf05e47hbkc9to5ljyfp7exud4yofaidnogdtqicl5ypwku&rid=giphy.gif&ct=g)

**Comment by BrunoRizzo765** [comment]
Hola Simón, gracias por tu recomendación pero me parece que quedaría un poco sobrecargado de tanto punteo.
