### ISSUE TITLE
Recomendación ítem series 

### ISSUE THREAD

**Issue by nmolina02** [pdepviernestm/presentacion-2022-BrunoRizzo765#2]
Hola Bruno, buena presentación. Las cosas que te recomendaría que cambies es que coloques "Legajo:", y no con los dos puntos separados de la palabra como lo habías puesto.
Además, en el ítem de series, podrías colocar una información adicional como qué tipo de series te gusta mirar o poner el nombre de alguna serie que te haya gustado mucho.
Saludos!

**Comment by BrunoRizzo765** [comment]
Hola gracias por tu recomendación, ya mismo hago los cambios.
